# -*- coding: utf-8 -*-
"""ingestion_transformation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sHbAThtVsBcEutGX81hntTHF83ZZAZS
"""

import pandas as pd
from sqlalchemy import create_engine
import os

# Load CSV
data = pd.read_csv("/content/Sample_Data_Ingestion.csv")

# Convert timestamp
data['Log_Timestamp'] = pd.to_datetime(data['Log_Timestamp'], format='%d-%m-%Y %H:%M')

# Remove duplicates
data = data.drop_duplicates()

# Create metrics
data['Total_Network_Traffic'] = data['Network_Traffic_In (MB/s)'] + data['Network_Traffic_Out (MB/s)']
data['Availability'] = data['Uptime (Hours)'] / (data['Uptime (Hours)'] + data['Downtime (Hours)'])
data['High_CPU_Alert'] = data['CPU_Utilization (%)'] > 80

# Ensure database folder exists
os.makedirs("database", exist_ok=True)

# Save to SQLite
engine = create_engine("sqlite:///database/server_monitoring.db")
data.to_sql("server_logs", engine, if_exists="replace", index=False)

print("Data pipeline executed successfully")